import { Member, Visitation, TrainingRecord, MinistryRoster, Sacrament } from "@/types";

export const DEMO_MEMBERS: Member[] = [
  {
    name: "김철수", name_en: "Chulsoo Kim", status: "활동", membership_stage: "Fellow",
    member_class: "멤버가족", gender: "남", birthday: "1995-03-15", phone: "765-555-0101",
    email: "chulsoo@purdue.edu", address: "123 State St, West Lafayette, IN",
    department: "청년부", district: "작은불꽃", role: "구역장", baptism: "세례",
    ministry: "찬양팀", registered_date: "2024-08-01", previous_church: "서울중앙교회",
    school: "Purdue University", grade: "박사", major: "Computer Science",
    graduation_year: "2027", family_tag: "KIM01", family_role: "본인",
    last_contact: "2026-03-10", memo: "", welcome_table: "2024-08-04",
    gospel_start: "exempt", fellow_table: "2025-01-15",
    gospel_into_leadership: "", photo_url: "", created_at: "2024-08-01",
  },
  {
    name: "이영희", name_en: "Younghee Lee", status: "활동", membership_stage: "Leader",
    member_class: "멤버가족", gender: "여", birthday: "1993-07-22", phone: "765-555-0102",
    email: "younghee@purdue.edu", address: "456 Grant St, West Lafayette, IN",
    department: "청년부", district: "실로암", role: "리더", baptism: "세례",
    ministry: "교육부", registered_date: "2023-01-15", previous_church: "부산성산교회",
    school: "Purdue University", grade: "박사", major: "Mechanical Engineering",
    graduation_year: "2026", family_tag: "", family_role: "",
    last_contact: "2026-03-18", memo: "", welcome_table: "2023-01-22",
    gospel_start: "exempt", fellow_table: "2023-06-01",
    gospel_into_leadership: "2024-01-10", photo_url: "", created_at: "2023-01-15",
  },
  {
    name: "박민수", name_en: "Minsoo Park", status: "활동", membership_stage: "Member",
    member_class: "멤버가족", gender: "남", birthday: "1998-11-05", phone: "765-555-0103",
    email: "minsoo@purdue.edu", address: "789 Northwestern Ave, West Lafayette, IN",
    department: "청년부", district: "코너스톤", role: "", baptism: "",
    ministry: "", registered_date: "2025-09-01", previous_church: "",
    school: "Purdue University", grade: "석사", major: "Electrical Engineering",
    graduation_year: "2027", family_tag: "", family_role: "",
    last_contact: "2025-12-01", memo: "연락이 뜸해짐", welcome_table: "2025-09-07",
    gospel_start: "", fellow_table: "",
    gospel_into_leadership: "", photo_url: "", created_at: "2025-09-01",
  },
  {
    name: "정수진", name_en: "Sujin Jung", status: "활동", membership_stage: "Visitor",
    member_class: "새가족", gender: "여", birthday: "2000-04-12", phone: "765-555-0104",
    email: "sujin@purdue.edu", address: "321 Salisbury St, West Lafayette, IN",
    department: "청년부", district: "작은불꽃", role: "", baptism: "",
    ministry: "", registered_date: "2026-03-01", previous_church: "",
    school: "Purdue University", grade: "학부", major: "Biology",
    graduation_year: "2028", family_tag: "", family_role: "",
    last_contact: "2026-03-15", memo: "새가족 환영", welcome_table: "",
    gospel_start: "", fellow_table: "",
    gospel_into_leadership: "", photo_url: "", created_at: "2026-03-01",
  },
  {
    name: "최동현", name_en: "Donghyun Choi", status: "활동", membership_stage: "Fellow",
    member_class: "멤버가족", gender: "남", birthday: "1990-08-30", phone: "765-555-0105",
    email: "donghyun@purdue.edu", address: "555 River Rd, West Lafayette, IN",
    department: "장년부", district: "3구역", role: "집사", baptism: "세례",
    ministry: "안내팀", registered_date: "2022-03-01", previous_church: "대전중앙교회",
    school: "Purdue University", grade: "교직원", major: "Chemistry",
    graduation_year: "2020", family_tag: "CHOI01", family_role: "남편",
    last_contact: "2026-03-20", memo: "", welcome_table: "2022-03-06",
    gospel_start: "exempt", fellow_table: "2022-09-01",
    gospel_into_leadership: "", photo_url: "", created_at: "2022-03-01",
  },
  {
    name: "최미영", name_en: "Miyoung Choi", status: "활동", membership_stage: "Member",
    member_class: "멤버가족", gender: "여", birthday: "1992-12-18", phone: "765-555-0106",
    email: "miyoung@purdue.edu", address: "555 River Rd, West Lafayette, IN",
    department: "장년부", district: "3구역", role: "", baptism: "유아세례",
    ministry: "", registered_date: "2022-03-01", previous_church: "",
    school: "", grade: "", major: "",
    graduation_year: "", family_tag: "CHOI01", family_role: "아내",
    last_contact: "2026-03-20", memo: "", welcome_table: "2022-03-06",
    gospel_start: "exempt", fellow_table: "",
    gospel_into_leadership: "", photo_url: "", created_at: "2022-03-01",
  },
  {
    name: "한지민", name_en: "Jimin Han", status: "Alumni", membership_stage: "Fellow",
    member_class: "멤버가족", gender: "여", birthday: "1996-05-25", phone: "312-555-0107",
    email: "jimin.han@gmail.com", address: "Chicago, IL",
    department: "알럼나이", district: "", role: "", baptism: "세례",
    ministry: "", registered_date: "2021-08-01", previous_church: "",
    school: "Purdue University", grade: "석사", major: "Industrial Engineering",
    graduation_year: "2023", family_tag: "", family_role: "",
    last_contact: "2025-12-25", memo: "시카고 정착", welcome_table: "2021-08-08",
    gospel_start: "exempt", fellow_table: "2022-03-01",
    gospel_into_leadership: "", photo_url: "", created_at: "2021-08-01",
  },
  {
    name: "윤서준", name_en: "Seojun Yoon", status: "확인필요", membership_stage: "Member",
    member_class: "멤버가족", gender: "남", birthday: "1997-09-14", phone: "765-555-0108",
    email: "seojun@purdue.edu", address: "100 Chauncey Ave, West Lafayette, IN",
    department: "청년부", district: "실로암", role: "", baptism: "",
    ministry: "", registered_date: "2025-01-15", previous_church: "",
    school: "Purdue University", grade: "박사", major: "Physics",
    graduation_year: "2029", family_tag: "", family_role: "",
    last_contact: "2025-11-01", memo: "연락 두절", welcome_table: "2025-01-19",
    gospel_start: "", fellow_table: "",
    gospel_into_leadership: "", photo_url: "", created_at: "2025-01-15",
  },
  {
    name: "장가람", name_en: "Garam Jang", status: "활동", membership_stage: "Leader",
    member_class: "교역자", gender: "남", birthday: "1988-01-10", phone: "765-555-0100",
    email: "karamjang@gmail.com", address: "200 Vine St, West Lafayette, IN",
    department: "장년부", district: "1구역", role: "전도사", baptism: "세례",
    ministry: "담당교역자", registered_date: "2020-03-01", previous_church: "",
    school: "Purdue University", grade: "박사", major: "Theology",
    graduation_year: "", family_tag: "", family_role: "",
    last_contact: "2026-03-24", memo: "", welcome_table: "",
    gospel_start: "exempt", fellow_table: "",
    gospel_into_leadership: "", photo_url: "", created_at: "2020-03-01",
  },
  {
    name: "김하늘", name_en: "Haneul Kim", status: "활동", membership_stage: "Visitor",
    member_class: "새가족", gender: "여", birthday: "2001-06-20", phone: "765-555-0109",
    email: "haneul@purdue.edu", address: "400 Litton Ln, West Lafayette, IN",
    department: "청년부", district: "코너스톤", role: "", baptism: "",
    ministry: "", registered_date: "2026-03-17", previous_church: "",
    school: "Purdue University", grade: "학부", major: "Nursing",
    graduation_year: "2027", family_tag: "", family_role: "",
    last_contact: "2026-03-17", memo: "첫 방문", welcome_table: "",
    gospel_start: "", fellow_table: "",
    gospel_into_leadership: "", photo_url: "", created_at: "2026-03-17",
  },
];

export const DEMO_VISITATIONS: Visitation[] = [
  {
    id: "V001", date: "2026-03-20", member_name: "김철수", pastor: "장가람",
    visitation_type: "정기심방", location: "교회", summary: "학업 근황 나눔, 논문 진행 상황 좋음",
    prayer_requests: "논문 심사 통과", follow_up: "", follow_up_date: "",
    follow_up_done: "", recorded_by: "장가람", created_at: "2026-03-20",
  },
  {
    id: "V002", date: "2026-03-18", member_name: "이영희", pastor: "장가람",
    visitation_type: "진로상담", location: "카페", summary: "졸업 후 진로 고민 상담",
    prayer_requests: "취업 방향 인도", follow_up: "이력서 피드백", follow_up_date: "2026-03-25",
    follow_up_done: "", recorded_by: "장가람", created_at: "2026-03-18",
  },
  {
    id: "V003", date: "2026-03-15", member_name: "정수진", pastor: "장가람",
    visitation_type: "새가족", location: "교회", summary: "새가족 환영 면담, 교회 소개",
    prayer_requests: "대학생활 적응", follow_up: "구역모임 연결", follow_up_date: "2026-03-22",
    follow_up_done: "완료", recorded_by: "장가람", created_at: "2026-03-15",
  },
  {
    id: "V004", date: "2026-03-10", member_name: "최동현", pastor: "장가람",
    visitation_type: "정기심방", location: "자택", summary: "가정 심방, 아이 양육 이야기",
    prayer_requests: "가정의 평안", follow_up: "", follow_up_date: "",
    follow_up_done: "", recorded_by: "장가람", created_at: "2026-03-10",
  },
  {
    id: "V005", date: "2026-03-05", member_name: "박민수", pastor: "장가람",
    visitation_type: "위기심방", location: "카페", summary: "학업 스트레스 상담, 휴학 고려 중",
    prayer_requests: "마음의 평안, 결정의 지혜", follow_up: "2주 후 재면담",
    follow_up_date: "2026-03-19", follow_up_done: "",
    recorded_by: "장가람", created_at: "2026-03-05",
  },
];

export const DEMO_TRAINING: TrainingRecord[] = [
  { id: "T001", member_name: "김철수", course: "새가족반", completed_date: "2024-09-01", notes: "", created_at: "2024-09-01" },
  { id: "T002", member_name: "김철수", course: "성경통독", completed_date: "2025-03-01", notes: "", created_at: "2025-03-01" },
  { id: "T003", member_name: "이영희", course: "새가족반", completed_date: "2023-03-01", notes: "", created_at: "2023-03-01" },
  { id: "T004", member_name: "이영희", course: "성경통독", completed_date: "2023-09-01", notes: "", created_at: "2023-09-01" },
  { id: "T005", member_name: "이영희", course: "리더십훈련", completed_date: "2024-01-10", notes: "", created_at: "2024-01-10" },
];

export const DEMO_MINISTRY: MinistryRoster[] = [
  { id: "M001", department_ministry: "찬양팀", team: "주일찬양", period: "2026 상반기", member_name: "김철수", role_in_team: "보컬", start_date: "2026-01-01", end_date: "2026-06-30", notes: "" },
  { id: "M002", department_ministry: "안내팀", team: "주일안내", period: "2026 상반기", member_name: "최동현", role_in_team: "팀장", start_date: "2026-01-01", end_date: "2026-06-30", notes: "" },
  { id: "M003", department_ministry: "교육부", team: "주일학교", period: "2026 상반기", member_name: "이영희", role_in_team: "교사", start_date: "2026-01-01", end_date: "2026-06-30", notes: "" },
];

export const DEMO_SACRAMENTS: Sacrament[] = [
  { id: "S001", date: "2024-12-25", member_name: "김철수", type: "세례", detail: "성탄절 세례식", notes: "", created_at: "2024-12-25" },
  { id: "S002", date: "2023-04-09", member_name: "이영희", type: "세례", detail: "부활절 세례식", notes: "", created_at: "2023-04-09" },
];
