export const PURDUE_MAJORS = [
  "Accountancy", "Actuarial Science", "Aeronautical and Astronautical Engineering",
  "Agricultural Economics", "Agricultural Engineering", "Agronomy",
  "American Studies", "Animal Sciences", "Anthropology",
  "Applied Statistics", "Art and Design", "Biochemistry",
  "Biological Engineering", "Biology", "Biomedical Engineering",
  "Brain and Behavioral Sciences", "Chemical Engineering", "Chemistry",
  "Child Development and Family Studies", "Civil Engineering",
  "Communication", "Comparative Literature", "Computer and Information Technology",
  "Computer Engineering", "Computer Graphics Technology", "Computer Science",
  "Construction Engineering and Management", "Counseling Psychology",
  "Creative Writing", "Crop Science", "Cybersecurity",
  "Data Science", "Dietetics", "Earth, Atmospheric, and Planetary Sciences",
  "Ecology", "Economics", "Educational Studies",
  "Electrical and Computer Engineering", "Electrical Engineering",
  "English", "Entomology", "Entrepreneurship",
  "Environmental and Ecological Engineering", "Environmental Science",
  "Film and Video Studies", "Finance", "Food Science",
  "Forestry and Natural Resources", "General Management",
  "Genetics", "Health and Disease", "Health Sciences",
  "History", "Honors", "Hospitality and Tourism Management",
  "Human Resource Development", "Industrial Design",
  "Industrial Engineering", "Information Technology",
  "Integrated Business and Engineering", "Interdisciplinary Science",
  "Interior Design", "Japanese", "Kinesiology",
  "Landscape Architecture", "Law", "Liberal Arts",
  "Linguistics", "Management", "Marketing",
  "Materials Engineering", "Mathematics", "Mechanical Engineering",
  "Media", "Microbiology", "Mining Engineering",
  "Movement and Sport Sciences", "Multidisciplinary Engineering",
  "Music", "Natural Resources and Environmental Science",
  "Neuroscience", "Nuclear Engineering", "Nursing",
  "Nutrition Science", "Operations Management",
  "Organizational Leadership", "Pharmaceutical Sciences", "Pharmacy",
  "Philosophy", "Physics", "Plant Biology",
  "Political Science", "Professional Writing", "Psychological Sciences",
  "Public Health", "Radiological Health Sciences",
  "Religious Studies", "Retail Management", "Selling and Sales Management",
  "Sociology", "Software Engineering", "Soil Science",
  "Spanish", "Speech, Language, and Hearing Sciences",
  "Statistics", "Supply Chain Management", "Technology Leadership and Innovation",
  "Theatre", "Veterinary Medicine", "Visual Communication Design",
  "Web Programming and Design", "Wildlife", "Women's Studies",
  // Korean programs
  "경영학", "경제학", "교육학", "기계공학", "물리학", "생물학",
  "수학", "신학", "약학", "의학", "전기공학", "전자공학",
  "정치학", "컴퓨터공학", "통계학", "화학", "화학공학", "회계학",
  "사회학", "심리학", "간호학", "건축학", "토목공학", "항공우주공학",
  "산업공학", "재료공학", "환경공학", "농업경제학", "식품과학",
];
